# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/Auth'
target 'productApp' do

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

end

